version: "2"
services:
  cog:
    image: "${COG_IMAGE}"
    environment:
      - COG_MQTT_HOST=0.0.0.0
      - DATABASE_URL=${DATABASE_URL}
      - COG_DB_SSL=${COG_DB_SSL}
      - SLACK_API_TOKEN=${SLACK_API_TOKEN}
      - COG_BOOTSTRAP_USERNAME=${COG_BOOTSTRAP_USERNAME}
      - COG_BOOTSTRAP_PASSWORD=${COG_BOOTSTRAP_PASSWORD}
      - COG_BOOTSTRAP_EMAIL_ADDRESS=${COG_BOOTSTRAP_EMAIL_ADDRESS}
      - COG_BOOTSTRAP_FIRST_NAME=${COG_BOOTSTRAP_FIRST_NAME}
      - COG_BOOTSTRAP_LAST_NAME=${COG_BOOTSTRAP_LAST_NAME}
      - COG_API_URL_BASE=${COG_API_URL_BASE}
      - COG_TRIGGER_URL_BASE=${COG_TRIGGER_URL_BASE}
      - COG_SERVICE_URL_BASE=${COG_SERVICE_URL_BASE}
      - RELAY_ID=${RELAY_ID}
      - RELAY_COG_TOKEN=${RELAY_COG_TOKEN}
      - COG_ALLOW_SELF_REGISTRATION=${COG_ALLOW_SELF_REGISTRATION}
    ports:
      - 1883:1883
      - 4000:4000
      - 4001:4001
      - 4002:4002
    restart: always
    entrypoint: /home/operable/cog/scripts/docker-start
  relay:
    image: "${RELAY_IMAGE}"
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - RELAY_ID=${RELAY_ID}
      - RELAY_COG_TOKEN=${RELAY_COG_TOKEN}
      - RELAY_COG_REFRESH_INTERVAL=30s
      - RELAY_DOCKER_CLEAN_INTERVAL=1m
      - RELAY_COG_HOST=cog
      - RELAY_MANAGED_DYNAMIC_CONFIG=true
      - RELAY_DYNAMIC_CONFIG_ROOT=/tmp/bundle_configs
    links:
      - cog
    restart: always
    entrypoint: /usr/local/bin/relay
